import NavMenu from '@/components/NavMenu/NavMenu';
import Footer from '@/components/Footer/Footer';

import './globals.css'
import { Open_Sans } from 'next/font/google'

const myFont = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <NavMenu />
        {children}
        <Footer />
      </body>
    </html>
  )
}
